development:
  news_api_key: Rails.application.secrets.news_api_key
  google_api_key: Rails.application.secrets.google_api_key
  waqi_api_key: Rails.application.secrets.waqi_api_key

production:
  news_api_key: Rails.application.secrets.news_api_key
  google_api_key: Rails.application.secrets.google_api_key
  waqi_api_key: Rails.application.secrets.waqi_api_key
test:
  news_api_key: Rails.application.secrets.news_api_key
  google_api_key: Rails.application.secrets.google_api_key
  waqi_api_key: Rails.application.secrets.waqi_api_key
