# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77b1a545650a1f76f4fc36631fcc93c890cbf7dc6f6ea4687403ec4dc05b18a7139c2b78981d37194f6ad58f3f85fb595b9f29f8dda6fe04221666be00189b0c
  news_api_key: <%= ENV["NEWS_API_KEY"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  waqi_api_key: <%= ENV["WAQI_API_KEY"] %>

test:
  secret_key_base: c35f8fe37342f96dbe672e240819bcc9a18ec3fc89a022d2dd7e05c67d1cd046c40929a29e0500de47a3021adab1599ef69c19d1dd8eca9fb333c6fc116f7bd2
  news_api_key: <%= ENV["NEWS_API_KEY"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  waqi_api_key: <%= ENV["WAQI_API_KEY"] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  news_api_key: <%= ENV["NEWS_API_KEY"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  waqi_api_key: <%= ENV["WAQI_API_KEY"] %>
